os:
  - linux

branches:
  only:
    - master

env:
  - NODE_VERSION="6.3.0"
  
before_script:
 - chmod +x ./packager/travis-build.sh

script: ./packager/travis-build.sh

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change