version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - npm install
  - npm install -g electron-download
  - electron-download --version=1.4.5 --arch=ia32 --platform=win32

build_script:
  - npm run dist-win

test: off